### ISSUE TITLE
Exception during pool initialization

### ISSUE THREAD

**Issue by berkay-karlik** [Cloud-RF/tak-server#11]
Hello,
I was trying to setup tak-server following the steps instructed in README.md. 

The error I got:
```
[main] ERROR com.bbn.tak.schema.SchemaManager - Failed to initalize pool: Connection to tak-database:5432 refused. Check that hostname and port are correct and the postmaster is accepting TCP/IP connections. Connection to tak-database:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

The tak release used: `takserver-docker-4.7-RELEASE-18.zip`
machine tested:
- AWS c5.xlarge:
  - 4vCPU
  - 8 GB RAM
  - Up to 10 Gbps network bandwidth
  - 50gb storage

I tried two different OS since the recommended one by tak was RHEL but README.md mentions Debian as well.

in RHEL 8:
![image](https://user-images.githubusercontent.com/75606426/184591439-83a65afd-9dcd-4f11-ab7f-86d61a8e7808.png)
in Debian 11:
![image](https://user-images.githubusercontent.com/75606426/184591722-40a42023-25bc-4176-9640-3c9c4a5b1cbf.png)

I'm stuck here during `./script/setup.sh`, any help greatly appreciated.

**Comment by patrykCRF** [comment]
Hi, we were able to reproduce the error and after investigation, we have discovered that the "pg_hba.conf" file has been changed in the latest release by TAK. The relevant changes were made and our latest version should run without an issue.
Details of the change:
```bash 
diff pg_hba.conf ./tak/db-utils/pg_hba.conf 
83d82
< host    all             all             172.0.0.0/8             md5
```

**Comment by berkay-karlik** [comment]
Many thanks for returning in such short notice. Is this fix currently available in public? If not when would it be?

**Comment by berkay-karlik** [comment]
it works with the latest version, thank you for the hard work.
