### ISSUE TITLE
Unable to install on Ubuntu 18.04 4.8 tak

### ISSUE THREAD

**Issue by CaptainsMast** [Cloud-RF/tak-server#27]
Unable to install on ubuntu 18.04, I get to input the cert information and then when creating the containers it gives this error:

[+] Building 0.4s (6/6) FINISHED                                                                                                                                                     
 => [tak-server-tak internal] load build definition from Dockerfile.takserver                                                                                                   0.0s
 => => transferring dockerfile: 250B                                                                                                                                            0.0s
 => [tak-server-db internal] load build definition from Dockerfile.takserver-db                                                                                                 0.1s
 => => transferring dockerfile: 224B                                                                                                                                            0.0s
 => [tak-server-tak internal] load .dockerignore                                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => [tak-server-db internal] load .dockerignore                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => ERROR [tak-server-tak internal] load metadata for docker.io/library/openjdk:11-jdk-bullseye                                                                                 0.1s
 => CANCELED [tak-server-db internal] load metadata for docker.io/library/postgres:15                                                                                           0.0s
------
 > [tak-server-tak internal] load metadata for docker.io/library/openjdk:11-jdk-bullseye:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
load metadata for docker.io/library/openjdk:11-jdk-bullseye

any help would be greatly appreciated

**Comment by AlexWinder** [comment]
Could you post the hardware specs and Docker version of the machine which you are having troubles installing on to?

We have tested on average spec machines running Ubuntu 20 and 22, Ubuntu 18 shouldn't be too dissimilar.

**Comment by CaptainsMast** [comment]
I had posgres already installed, I removed it from the OS and it builds the containers. However, it is erroring out while generating the certs. The tak-server container is stuck in a restart loop. 6 Core ARM64 processor, 500gb storage, 8gb RAM,  Docker 20.10.12

**Comment by CaptainsMast** [comment]
Also Tak 4.8 is the container version

**Comment by curtishall** [comment]
Looks similar to https://github.com/docker/cli/issues/2229

```sudo apt-get remove docker docker-engine docker.io containerd runc```

You may also need to remove golang-docker-credential-helpers
