### ISSUE TITLE
Importing Certificate issue

### ISSUE THREAD

**Issue by wimbime1** [Cloud-RF/tak-server#36]
Hello, 

I am using a Ubuntu 20.04. I have followed all the steps in the README. I am not trying to import the certificate to the Fire Fox. However, it is not importing. I am using admin.p12 and typed the password `atakatak` but I will not import. Can someone assist with this issue?

**Comment by FarrantAlex** [comment]
Try this:
https://doc.primekey.com/ejbca-cloud/ejbca-cloud-aws/quick-start-guide/import-certificate-to-mozilla-firefox
