### ISSUE TITLE
Secure Connection Fail Issue

### ISSUE THREAD

**Issue by MiguelWimbish** [Cloud-RF/tak-server#41]
I am attempting to connect to the ATAK server from a different machine. However, I receive an error that states, "Secure Connection Failed"

And the error code is "SSL_EEROR_BAD_CERT_ALERT"

How can I resolve this issue of getting pass this error?

**Comment by mainframe** [comment]
Same problem here after setup.sh:
curl -k https://127.0.0.1:8443
curl: (56) OpenSSL SSL_read: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate, errno 0

**Comment by mainframe** [comment]
My bad, did not rtfm...

> The admin.p12 certificate needs to be copied from ./tak/certs/files/ and installed in a web browser for you to be able to administer your TAK Server.
