### ISSUE TITLE
cant install certificates with UserManager - error with java

### ISSUE THREAD

**Issue by KubaMiszcz** [Cloud-RF/tak-server#43]
it doesnt work with TAK server 4.10-release50 and 4.8 as well - some issues with java during line 339 in setup.sh:
`sudo java -jar /opt/tak/utils/UserManager.jar certmod -A /opt/tak/certs/files/admin.pem`

like:
`Error: LinkageError occurred while loading main class com.bbn.marti.UserManager
java.lang.UnsupportedClassVersionError: com/bbn/marti/UserManager has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

I have java 17 installed JDK and JRE

- Hardware Make/Model: LXC on proxmox
- Operating System and Version (e.g. `cat /etc/os-release`): Debian11
- RAM (e.g. `free -h`): 4GB
- Disk Availability (e.g. `df -h`): 6GB
- TAK Server Version From TAK.gov: 4.10-release50

**Comment by alphafox02** [comment]
Just ran it on 22.04 w/ TAK 5.0 and it completed and runs. Look at my fork and you’ll see the change I made for Java 17. I’m not actually running Java 17 on the host.

**Comment by KubaMiszcz** [comment]
thx, I'll try, and look for changes.
I noticed that my java17 is on the host not in container, container uses old java, but package is 5.0;] 
then when I update it in dockerfile it almost works but still crash in UserManager, but I have same error in direct install and it is caused that webgui hasnt fully started yet, when I waited few minutes, try to run it in browser to be sure it is fully loaded, then Usermanager go further to the end. Maybe this is reason

I'll check it in free time

**Comment by KubaMiszcz** [comment]
I bump java to 17 in dockerfile, and increase sleep before ...usermanager... (328 line in setup.sh), and it works now with 4.10 and 5.0 verision of takserver
