### ISSUE TITLE
UserManager when installing

### ISSUE THREAD

**Issue by kwrjoseph** [Cloud-RF/tak-server#44]
UserManager when installing

  # error
LinkageError occurred while loading main class com.bbn.marti.UserManager         java.lang.UnsupportedClassVersionError: com/bbn/marti/UserManager has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by AlexWinder** [comment]
There is a bug report template which should be completed in full to allow for the environment and the bug to be replicated. Closing this issue as the provided details are not enough to replicate the issue.
