### ISSUE TITLE
Feature Request: Make certificate country configurable in setup script

### ISSUE THREAD

**Issue by dnlbaldwin** [Cloud-RF/tak-server#53]
Currently the cert-metadata.sh file is hardcoded to US.  Would it be possible to update the setup script to prompt the user for a country and then subsequently update the cert-metadata file and environment variables?

I believe I've been able to achieve this result using a find and replace command with sed and an additional prompt to the user for input.  I can create a PR if you want.

**Comment by AlexWinder** [comment]
Please provide a PR with your proposed changes and we can review.

**Comment by FarrantAlex** [comment]
Merged. Thanks for the PR.
