### ISSUE TITLE
clean install gives PostgreSQL database configuration suggestion Message

### ISSUE THREAD

**Issue by Mvanmierlo** [Cloud-RF/tak-server#54]
Just did my first install via your method (thanks for creating this) which resulted in a working TAK 5.2 server.
All seems to be working fine but I get a big red message when logging in the WebGui with the message "PostgreSQL database configuration suggestion [available.]"

![image](https://github.com/user-attachments/assets/0bf5f23b-f305-41ac-b979-40e447732361)

When I click the message I get the following :

Database Configuration
PostgreSQL Version: 15.1 (Debian 15.1-1.pgdg110+1)

Latest SA (share location of other users at connection time): enabled
Database Connection Pool size is auto-detected at startup (edit configuration below to change this setting).

Increasing the max_connections property in the PostgreSQL database configuration to at least 410 is suggested.
Increasing the max_buffers property is also suggested.

![image](https://github.com/user-attachments/assets/2986541c-2847-4f96-a0b8-9f23f71f67a7)

Just checked the postgresql.conf in the docker instance but this shows a max_connections set to 2100.

![image](https://github.com/user-attachments/assets/a42db5c4-8740-4cc8-95a2-3fdffb6fc5e7)

So the configuration suggestion makes no sense .. as the suggestion is max_connections at least 410.
The postgresql.conf has no mention of the other suggestion max_buffers within the config file so that leaves me completely puzzled.

Any suggestions ?
 
I am running my containers on a normal server running a full updated Bookworm Debian.

**Comment by AlexWinder** [comment]
Try using the provided PostgreSQL file - https://github.com/Cloud-RF/tak-server/blob/main/postgresql1.conf

**Comment by FarrantAlex** [comment]
Since publishing our PG hacks, the defaults it ships with have improved and now the limit is now a generous 2100.
We now use the TPC provided postgresql.conf so this issue is resolved.
