### ISSUE TITLE
Updated Versions?

### ISSUE THREAD

**Issue by AetherHund** [Cloud-RF/tak-server#56]
I followed the instructions in the ReadMe file, and even the attached video. The setup.sh script won't run, however. I believe it may be because the current versions on TAK.gov are not currently supported by the scripts. I currently get the error:

"Please download the release of docker image as per instructions in README.md file. Exiting now..."

I tried to pull an older version from tak.gov, but the oldest I found was RELEASE-112.  I have been trying to stand up a test TAK server on a VM VirtualBox for about a week now, using different flavors of Linux, with no success. I was hoping that a dockerized version might be the answer, but I have not been successful there either. 

Are there any plans to include the newer versions of tak-server for your dockerized solution? If not, any suggestions on how to fix this would be greatly appreciated.

<img width="569" alt="Screenshot_3" src="https://github.com/user-attachments/assets/8686ec92-a2a5-4cbb-b115-e7f1bd1b4205">

**Comment by AlexWinder** [comment]
We've not updated this to yet support TAK server > 5.1

If you are using a newer version then in theory you can circumvent this by adding in the checksum for your TAK server version into `tak-md5checksum.txt` and `tak-sha1checksum.txt`. 

Or, you could comment out the function to compare checksum on L142:

https://github.com/Cloud-RF/tak-server/blob/5a84032346f4a49d6b5ede7dfb7bf96bc6c8cfec/scripts/setup.sh#L142

However, it's worth noting that > 5.1 isn't tested/supported and so it might not work at all with the scripts. If you find it works we would appreciate a PR with any changes you made to get it working.

**Comment by AetherHund** [comment]
Thank you. I appreciate the assistance. I will do my best to give you a PR if I get it working. I am actually very new to this, as I am not actually a developer. My organization needed someone to stand up a TAK server for testing, and I was volun-told to get it done. I will let you know what I find, and get a PR to you if it works. I will by trying 5.2-30 (latest version) first and work backwards from there. Hopefully it works and I can verify a working version and changes for you.

**Comment by AetherHund** [comment]
No joy, sadly. I will fight with it more over the weekend and see if I can figure out what other adjustments can be made. Even with altered tak-md5checksum.txt and tak-sha1checksum.txt, something isn't recognizing the new versions as valid. I will see if I can get in touch with a friend who is way more familiar with bash than I am. Hopefully we can find a solve for it. Thanks again for your advice!

**Comment by FarrantAlex** [comment]
Updated to 5.1 and 5.2 today. Thanks for your patience.
