### ISSUE TITLE
System agnostic logo replacement script

### ISSUE THREAD

**Issue by AlexWinder** [Cloud-RF/tak-server#8]
The `logo-replacement.sh` script installs `openjdk-11-jdk` and `imagemagick` natively on the host if they don't exist.

https://github.com/Cloud-RF/tak-server/blob/2d9c769781d98899a0174099afd12677c5975b8f/scripts/logo-replacement.sh#L8-L20

A better solution would be to have a Docker container to handle the replacement. This would make the script completely independent of the host operating system.

**Comment by FarrantAlex** [comment]
Meh. Too much effort for a pic of a banana.
